import Foundation

// All 78 tarot cards. Fill in `upright`, `reversed`, and `personalNote` with your own interpretations.
let allCards: [TarotCard] = majorArcana + wands + cups + swords + pentacles

// MARK: - Major Arcana

let majorArcana: [TarotCard] = [
    TarotCard(id: "the-fool", name: "The Fool", number: 0, arcana: .major, suit: .none,
              element: "Air", keywords: ["new beginnings", "innocence", "adventure", "spontaneity"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-magician", name: "The Magician", number: 1, arcana: .major, suit: .none,
              element: "Air / Mercury", keywords: ["willpower", "manifestation", "skill", "resourcefulness"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-high-priestess", name: "The High Priestess", number: 2, arcana: .major, suit: .none,
              element: "Water / Moon", keywords: ["intuition", "mystery", "inner knowledge", "the subconscious"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-empress", name: "The Empress", number: 3, arcana: .major, suit: .none,
              element: "Earth / Venus", keywords: ["fertility", "abundance", "nurturing", "nature"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-emperor", name: "The Emperor", number: 4, arcana: .major, suit: .none,
              element: "Fire / Aries", keywords: ["authority", "structure", "stability", "fatherhood"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-hierophant", name: "The Hierophant", number: 5, arcana: .major, suit: .none,
              element: "Earth / Taurus", keywords: ["tradition", "conformity", "institutions", "spiritual guidance"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-lovers", name: "The Lovers", number: 6, arcana: .major, suit: .none,
              element: "Air / Gemini", keywords: ["love", "union", "choices", "alignment"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-chariot", name: "The Chariot", number: 7, arcana: .major, suit: .none,
              element: "Water / Cancer", keywords: ["willpower", "victory", "control", "determination"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "strength", name: "Strength", number: 8, arcana: .major, suit: .none,
              element: "Fire / Leo", keywords: ["courage", "inner strength", "patience", "compassion"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-hermit", name: "The Hermit", number: 9, arcana: .major, suit: .none,
              element: "Earth / Virgo", keywords: ["solitude", "introspection", "inner guidance", "withdrawal"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "wheel-of-fortune", name: "Wheel of Fortune", number: 10, arcana: .major, suit: .none,
              element: "Fire / Jupiter", keywords: ["cycles", "fate", "turning points", "luck"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "justice", name: "Justice", number: 11, arcana: .major, suit: .none,
              element: "Air / Libra", keywords: ["fairness", "truth", "cause and effect", "law"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-hanged-man", name: "The Hanged Man", number: 12, arcana: .major, suit: .none,
              element: "Water / Neptune", keywords: ["suspension", "surrender", "new perspective", "sacrifice"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "death", name: "Death", number: 13, arcana: .major, suit: .none,
              element: "Water / Scorpio", keywords: ["transformation", "endings", "transition", "letting go"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "temperance", name: "Temperance", number: 14, arcana: .major, suit: .none,
              element: "Fire / Sagittarius", keywords: ["balance", "moderation", "patience", "purpose"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-devil", name: "The Devil", number: 15, arcana: .major, suit: .none,
              element: "Earth / Capricorn", keywords: ["bondage", "addiction", "materialism", "shadow self"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-tower", name: "The Tower", number: 16, arcana: .major, suit: .none,
              element: "Fire / Mars", keywords: ["upheaval", "chaos", "revelation", "sudden change"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-star", name: "The Star", number: 17, arcana: .major, suit: .none,
              element: "Air / Aquarius", keywords: ["hope", "renewal", "serenity", "inspiration"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-moon", name: "The Moon", number: 18, arcana: .major, suit: .none,
              element: "Water / Pisces", keywords: ["illusion", "fear", "the unconscious", "confusion"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-sun", name: "The Sun", number: 19, arcana: .major, suit: .none,
              element: "Fire / Sun", keywords: ["joy", "success", "vitality", "clarity"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "judgement", name: "Judgement", number: 20, arcana: .major, suit: .none,
              element: "Fire / Pluto", keywords: ["reflection", "reckoning", "awakening", "absolution"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "the-world", name: "The World", number: 21, arcana: .major, suit: .none,
              element: "Earth / Saturn", keywords: ["completion", "integration", "accomplishment", "wholeness"],
              upright: "", reversed: "", personalNote: ""),
]

// MARK: - Wands

let wands: [TarotCard] = [
    TarotCard(id: "ace-of-wands", name: "Ace of Wands", number: 1, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["spark", "inspiration", "potential", "new ventures"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "two-of-wands", name: "Two of Wands", number: 2, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["planning", "future", "discovery", "decisions"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "three-of-wands", name: "Three of Wands", number: 3, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["expansion", "foresight", "overseas", "progress"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "four-of-wands", name: "Four of Wands", number: 4, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["celebration", "harmony", "homecoming", "community"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "five-of-wands", name: "Five of Wands", number: 5, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["conflict", "competition", "tension", "diversity"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "six-of-wands", name: "Six of Wands", number: 6, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["victory", "recognition", "progress", "self-confidence"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "seven-of-wands", name: "Seven of Wands", number: 7, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["perseverance", "defensiveness", "maintaining position"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "eight-of-wands", name: "Eight of Wands", number: 8, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["speed", "action", "air travel", "swift change"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "nine-of-wands", name: "Nine of Wands", number: 9, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["resilience", "persistence", "last stretch", "fatigue"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "ten-of-wands", name: "Ten of Wands", number: 10, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["burden", "responsibility", "hard work", "completion"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "page-of-wands", name: "Page of Wands", number: 11, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["enthusiasm", "exploration", "discovery", "free spirit"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "knight-of-wands", name: "Knight of Wands", number: 12, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["energy", "passion", "adventure", "impulsiveness"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "queen-of-wands", name: "Queen of Wands", number: 13, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["courage", "confidence", "independence", "social butterfly"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "king-of-wands", name: "King of Wands", number: 14, arcana: .minor, suit: .wands,
              element: "Fire", keywords: ["vision", "entrepreneur", "honour", "natural-born leader"],
              upright: "", reversed: "", personalNote: ""),
]

// MARK: - Cups

let cups: [TarotCard] = [
    TarotCard(id: "ace-of-cups", name: "Ace of Cups", number: 1, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["new love", "intuition", "creativity", "emotional beginnings"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "two-of-cups", name: "Two of Cups", number: 2, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["partnership", "attraction", "connection", "mutual love"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "three-of-cups", name: "Three of Cups", number: 3, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["friendship", "celebration", "community", "abundance"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "four-of-cups", name: "Four of Cups", number: 4, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["apathy", "contemplation", "disconnectedness", "missed opportunity"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "five-of-cups", name: "Five of Cups", number: 5, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["loss", "grief", "disappointment", "regret"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "six-of-cups", name: "Six of Cups", number: 6, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["nostalgia", "childhood", "innocence", "reunion"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "seven-of-cups", name: "Seven of Cups", number: 7, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["fantasy", "illusion", "wishful thinking", "choices"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "eight-of-cups", name: "Eight of Cups", number: 8, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["walking away", "disillusionment", "seeking deeper meaning"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "nine-of-cups", name: "Nine of Cups", number: 9, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["contentment", "wishes fulfilled", "satisfaction", "pleasure"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "ten-of-cups", name: "Ten of Cups", number: 10, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["harmony", "happy family", "alignment", "divine love"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "page-of-cups", name: "Page of Cups", number: 11, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["creativity", "intuitive", "sensitive", "dreamer"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "knight-of-cups", name: "Knight of Cups", number: 12, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["romance", "charm", "imagination", "beauty"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "queen-of-cups", name: "Queen of Cups", number: 13, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["compassion", "calm", "emotional security", "intuition"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "king-of-cups", name: "King of Cups", number: 14, arcana: .minor, suit: .cups,
              element: "Water", keywords: ["emotional balance", "generosity", "diplomacy", "wisdom"],
              upright: "", reversed: "", personalNote: ""),
]

// MARK: - Swords

let swords: [TarotCard] = [
    TarotCard(id: "ace-of-swords", name: "Ace of Swords", number: 1, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["clarity", "truth", "mental breakthrough", "communication"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "two-of-swords", name: "Two of Swords", number: 2, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["indecision", "stalemate", "avoidance", "blocked emotions"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "three-of-swords", name: "Three of Swords", number: 3, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["heartbreak", "sorrow", "grief", "betrayal"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "four-of-swords", name: "Four of Swords", number: 4, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["rest", "recovery", "contemplation", "passive"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "five-of-swords", name: "Five of Swords", number: 5, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["conflict", "defeat", "hollow victory", "self-interest"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "six-of-swords", name: "Six of Swords", number: 6, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["transition", "change", "rite of passage", "moving on"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "seven-of-swords", name: "Seven of Swords", number: 7, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["deception", "trickery", "tactics", "strategy"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "eight-of-swords", name: "Eight of Swords", number: 8, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["imprisonment", "entrapment", "self-victimization", "restriction"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "nine-of-swords", name: "Nine of Swords", number: 9, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["anxiety", "worry", "fear", "nightmares"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "ten-of-swords", name: "Ten of Swords", number: 10, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["painful ending", "betrayal", "rock bottom", "crisis"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "page-of-swords", name: "Page of Swords", number: 11, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["curious", "restless", "talkative", "all talk"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "knight-of-swords", name: "Knight of Swords", number: 12, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["ambition", "action", "drive", "fast-thinking"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "queen-of-swords", name: "Queen of Swords", number: 13, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["independent", "unbiased judgement", "clear boundaries", "direct"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "king-of-swords", name: "King of Swords", number: 14, arcana: .minor, suit: .swords,
              element: "Air", keywords: ["mental clarity", "authority", "truth", "ethical"],
              upright: "", reversed: "", personalNote: ""),
]

// MARK: - Pentacles

let pentacles: [TarotCard] = [
    TarotCard(id: "ace-of-pentacles", name: "Ace of Pentacles", number: 1, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["opportunity", "prosperity", "new financial start", "manifestation"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "two-of-pentacles", name: "Two of Pentacles", number: 2, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["balance", "adaptability", "time management", "juggling"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "three-of-pentacles", name: "Three of Pentacles", number: 3, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["teamwork", "craftsmanship", "learning", "implementation"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "four-of-pentacles", name: "Four of Pentacles", number: 4, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["holding on", "security", "conservatism", "scarcity"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "five-of-pentacles", name: "Five of Pentacles", number: 5, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["hardship", "poverty", "insecurity", "isolation"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "six-of-pentacles", name: "Six of Pentacles", number: 6, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["generosity", "charity", "giving", "receiving"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "seven-of-pentacles", name: "Seven of Pentacles", number: 7, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["patience", "long-term view", "sustainable results", "investment"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "eight-of-pentacles", name: "Eight of Pentacles", number: 8, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["diligence", "mastery", "skill development", "apprenticeship"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "nine-of-pentacles", name: "Nine of Pentacles", number: 9, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["abundance", "luxury", "self-sufficiency", "financial independence"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "ten-of-pentacles", name: "Ten of Pentacles", number: 10, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["wealth", "inheritance", "family", "long-term success"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "page-of-pentacles", name: "Page of Pentacles", number: 11, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["ambition", "desire", "diligent", "studious"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "knight-of-pentacles", name: "Knight of Pentacles", number: 12, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["hard work", "productivity", "routine", "conservative"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "queen-of-pentacles", name: "Queen of Pentacles", number: 13, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["practical", "nurturing", "providing", "down-to-earth"],
              upright: "", reversed: "", personalNote: ""),
    TarotCard(id: "king-of-pentacles", name: "King of Pentacles", number: 14, arcana: .minor, suit: .pentacles,
              element: "Earth", keywords: ["wealth", "business", "leadership", "security"],
              upright: "", reversed: "", personalNote: ""),
]
