import Foundation

// All 78 tarot cards. Add a `url` per card to enable the Labyrinthos button.
let allCards: [TarotCard] = majorArcana + wands + cups + swords + pentacles

// MARK: - Major Arcana

let majorArcana: [TarotCard] = [
    TarotCard(id: "the-fool", name: "The Fool", number: 0, arcana: .major, suit: .none,
              element: "Air",
              url: "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-fool-meaning-major-arcana-tarot-card-meanings"),
    TarotCard(id: "the-magician", name: "The Magician", number: 1, arcana: .major, suit: .none,
              element: "Air / Mercury",
              url: "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-magician-meaning-major-arcana-tarot-card-meanings"),
    TarotCard(id: "the-high-priestess", name: "The High Priestess", number: 2, arcana: .major, suit: .none,
              element: "Water / Moon",
              url: "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-high-priestess-meaning-major-arcana-tarot-card-meanings"),
    TarotCard(id: "the-empress", name: "The Empress", number: 3, arcana: .major, suit: .none,
              element: "Earth / Venus",
              url: "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-empress-meaning-major-arcana-tarot-card-meanings"),
    TarotCard(id: "the-emperor", name: "The Emperor", number: 4, arcana: .major, suit: .none,
              element: "Fire / Aries",
              url: "https://labyrinthos.co/blogs/tarot-card-meanings-list/the-emperor-meaning-major-arcana-tarot-card-meanings"),
    TarotCard(id: "the-hierophant", name: "The Hierophant", number: 5, arcana: .major, suit: .none,
              element: "Earth / Taurus",
              url: nil),
    TarotCard(id: "the-lovers", name: "The Lovers", number: 6, arcana: .major, suit: .none,
              element: "Air / Gemini",
              url: nil),
    TarotCard(id: "the-chariot", name: "The Chariot", number: 7, arcana: .major, suit: .none,
              element: "Water / Cancer",
              url: nil),
    TarotCard(id: "strength", name: "Strength", number: 8, arcana: .major, suit: .none,
              element: "Fire / Leo",
              url: nil),
    TarotCard(id: "the-hermit", name: "The Hermit", number: 9, arcana: .major, suit: .none,
              element: "Earth / Virgo",
              url: nil),
    TarotCard(id: "wheel-of-fortune", name: "Wheel of Fortune", number: 10, arcana: .major, suit: .none,
              element: "Fire / Jupiter",
              url: nil),
    TarotCard(id: "justice", name: "Justice", number: 11, arcana: .major, suit: .none,
              element: "Air / Libra",
              url: nil),
    TarotCard(id: "the-hanged-man", name: "The Hanged Man", number: 12, arcana: .major, suit: .none,
              element: "Water / Neptune",
              url: nil),
    TarotCard(id: "death", name: "Death", number: 13, arcana: .major, suit: .none,
              element: "Water / Scorpio",
              url: nil),
    TarotCard(id: "temperance", name: "Temperance", number: 14, arcana: .major, suit: .none,
              element: "Fire / Sagittarius",
              url: nil),
    TarotCard(id: "the-devil", name: "The Devil", number: 15, arcana: .major, suit: .none,
              element: "Earth / Capricorn",
              url: nil),
    TarotCard(id: "the-tower", name: "The Tower", number: 16, arcana: .major, suit: .none,
              element: "Fire / Mars",
              url: nil),
    TarotCard(id: "the-star", name: "The Star", number: 17, arcana: .major, suit: .none,
              element: "Air / Aquarius",
              url: nil),
    TarotCard(id: "the-moon", name: "The Moon", number: 18, arcana: .major, suit: .none,
              element: "Water / Pisces",
              url: nil),
    TarotCard(id: "the-sun", name: "The Sun", number: 19, arcana: .major, suit: .none,
              element: "Fire / Sun",
              url: nil),
    TarotCard(id: "judgement", name: "Judgement", number: 20, arcana: .major, suit: .none,
              element: "Fire / Pluto",
              url: nil),
    TarotCard(id: "the-world", name: "The World", number: 21, arcana: .major, suit: .none,
              element: "Earth / Saturn",
              url: nil),
]

// MARK: - Wands

let wands: [TarotCard] = [
    TarotCard(id: "ace-of-wands", name: "Ace of Wands", number: 1, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "two-of-wands", name: "Two of Wands", number: 2, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "three-of-wands", name: "Three of Wands", number: 3, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "four-of-wands", name: "Four of Wands", number: 4, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "five-of-wands", name: "Five of Wands", number: 5, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "six-of-wands", name: "Six of Wands", number: 6, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "seven-of-wands", name: "Seven of Wands", number: 7, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "eight-of-wands", name: "Eight of Wands", number: 8, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "nine-of-wands", name: "Nine of Wands", number: 9, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "ten-of-wands", name: "Ten of Wands", number: 10, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "page-of-wands", name: "Page of Wands", number: 11, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "knight-of-wands", name: "Knight of Wands", number: 12, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "queen-of-wands", name: "Queen of Wands", number: 13, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
    TarotCard(id: "king-of-wands", name: "King of Wands", number: 14, arcana: .minor, suit: .wands,
              element: "Fire",
              url: nil),
]

// MARK: - Cups

let cups: [TarotCard] = [
    TarotCard(id: "ace-of-cups", name: "Ace of Cups", number: 1, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "two-of-cups", name: "Two of Cups", number: 2, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "three-of-cups", name: "Three of Cups", number: 3, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "four-of-cups", name: "Four of Cups", number: 4, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "five-of-cups", name: "Five of Cups", number: 5, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "six-of-cups", name: "Six of Cups", number: 6, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "seven-of-cups", name: "Seven of Cups", number: 7, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "eight-of-cups", name: "Eight of Cups", number: 8, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "nine-of-cups", name: "Nine of Cups", number: 9, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "ten-of-cups", name: "Ten of Cups", number: 10, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "page-of-cups", name: "Page of Cups", number: 11, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "knight-of-cups", name: "Knight of Cups", number: 12, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "queen-of-cups", name: "Queen of Cups", number: 13, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
    TarotCard(id: "king-of-cups", name: "King of Cups", number: 14, arcana: .minor, suit: .cups,
              element: "Water",
              url: nil),
]

// MARK: - Swords

let swords: [TarotCard] = [
    TarotCard(id: "ace-of-swords", name: "Ace of Swords", number: 1, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "two-of-swords", name: "Two of Swords", number: 2, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "three-of-swords", name: "Three of Swords", number: 3, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "four-of-swords", name: "Four of Swords", number: 4, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "five-of-swords", name: "Five of Swords", number: 5, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "six-of-swords", name: "Six of Swords", number: 6, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "seven-of-swords", name: "Seven of Swords", number: 7, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "eight-of-swords", name: "Eight of Swords", number: 8, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "nine-of-swords", name: "Nine of Swords", number: 9, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "ten-of-swords", name: "Ten of Swords", number: 10, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "page-of-swords", name: "Page of Swords", number: 11, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "knight-of-swords", name: "Knight of Swords", number: 12, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "queen-of-swords", name: "Queen of Swords", number: 13, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
    TarotCard(id: "king-of-swords", name: "King of Swords", number: 14, arcana: .minor, suit: .swords,
              element: "Air",
              url: nil),
]

// MARK: - Pentacles

let pentacles: [TarotCard] = [
    TarotCard(id: "ace-of-pentacles", name: "Ace of Pentacles", number: 1, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "two-of-pentacles", name: "Two of Pentacles", number: 2, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "three-of-pentacles", name: "Three of Pentacles", number: 3, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "four-of-pentacles", name: "Four of Pentacles", number: 4, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "five-of-pentacles", name: "Five of Pentacles", number: 5, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "six-of-pentacles", name: "Six of Pentacles", number: 6, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "seven-of-pentacles", name: "Seven of Pentacles", number: 7, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "eight-of-pentacles", name: "Eight of Pentacles", number: 8, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "nine-of-pentacles", name: "Nine of Pentacles", number: 9, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "ten-of-pentacles", name: "Ten of Pentacles", number: 10, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "page-of-pentacles", name: "Page of Pentacles", number: 11, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "knight-of-pentacles", name: "Knight of Pentacles", number: 12, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "queen-of-pentacles", name: "Queen of Pentacles", number: 13, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
    TarotCard(id: "king-of-pentacles", name: "King of Pentacles", number: 14, arcana: .minor, suit: .pentacles,
              element: "Earth",
              url: nil),
]
